apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: app
  newName: ghcr.io/wasp-foundry/hello-alpha
  newTag: 19a3aac1401cf752018195371c4aff74371954fb
