apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: app
  newName: ghcr.io/wasp-foundry/notification-api
  newTag: 366d13a3c9857643f66753bd3c8165da70cb380c
