apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: app
  newName: ghcr.io/wasp-foundry/hello-beta
  newTag: 66a5131f5d94a2ba5bb5a065d9bc80800cec2693
