apiVersion: v1
kind: Service
metadata:
  name: notification-api
  labels:
    app.kubernetes.io/name: notification-api
    backstage.io/kubernetes-id: notification-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notification-api
  ports:
    - name: http
      port: 80
      targetPort: http
