apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: app
  newName: ghcr.io/wasp-foundry/hello-alpha
  newTag: 0c720ec5602b9f192a10d99a70b6de9cdd477f35
