apiVersion: v1
kind: Service
metadata:
  name: reviews
  labels:
    app.kubernetes.io/name: reviews
    backstage.io/kubernetes-id: reviews
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: reviews
  ports:
    - name: http
      port: 9080
      targetPort: http
