apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: app
  newName: ghcr.io/wasp-foundry/greeting-api
  newTag: 07f0d3f88fec15a36e49293635d10d5d1073cbf9
