apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: app
  newName: ghcr.io/wasp-foundry/hello-alpha
  newTag: fe822e23eec7f3eb29c6d77e4597a708020208e8
