apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-api
  labels:
    app.kubernetes.io/name: greeting-api
    backstage.io/kubernetes-id: greeting-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: greeting-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: greeting-api
        backstage.io/kubernetes-id: greeting-api
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: app
          image: app
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: APP_NAME
              value: greeting-api
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
