apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    app.kubernetes.io/name: ratings
    backstage.io/kubernetes-id: ratings
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ratings
  ports:
    - name: http
      port: 9080
      targetPort: http
